export const data = [
  {
    ISO3: "AGO",
    "countries-and-areas": "Angola",
    region: "SSA",
    "unicef-sub-region": "ESA",
    "income-group": "Lower middle income (LM)",
    total: "24%",
    "rural-residence": "2%",
    "urban-residence": "33%",
    "source-data": "Demographic and Health Questionaire",
    "source-time-period": "2015-16",
  },
  {
    ISO3: "ARG",
    "countries-and-areas": "Argentina",
    region: "LAC",
    "unicef-sub-region": "LAC",
    "income-group": "Upper middle income (UM)",
    total: "45%",
    "source-data": "Multiple Indicator Cluster Survey",
    "source-time-period": "2011-12",
  },
  {
    ISO3: "ARM",
    "countries-and-areas": "Armenia",
    region: "ECA",
    "unicef-sub-region": "EECA",
    "income-group": "Upper middle income (UM)",
    total: "85%",
    "rural-residence": "78%",
    "urban-residence": "91%",
    "source-data": "Demographic and Health Survey",
    "source-time-period": "2015-16",
  },
  {
    ISO3: "BGD",
    "countries-and-areas": "Bangladesh",
    region: "SA",
    "unicef-sub-region": "SA",
    "income-group": "Lower middle income (LM)",
    total: "42%",
    "rural-residence": "38%",
    "urban-residence": "57%",
    "source-data": "Multiple Indicator Cluster Survey",
    "source-time-period": "2019",
  },
  {
    ISO3: "BRB",
    "countries-and-areas": "Barbados",
    region: "LAC",
    "unicef-sub-region": "LAC",
    "income-group": "High income (H)",
    total: "76%",
    "rural-residence": "76%",
    "urban-residence": "76%",
    "source-data": "Multiple Indicator Cluster Survey",
    "source-time-period": "2012",
  },
  {
    ISO3: "BEN",
    "countries-and-areas": "Benin",
    region: "SSA",
    "unicef-sub-region": "WCA",
    "income-group": "Low income (L)",
    total: "5%",
    "rural-residence": "2%",
    "urban-residence": "10%",
    "source-data": "Demographic and Health Survey",
    "source-time-period": "2017-18",
  },
  {
    ISO3: "BIH",
    "countries-and-areas": "Bosnia and Herzegovina",
    region: "ECA",
    "unicef-sub-region": "EECA",
    "income-group": "Upper middle income (UM)",
    total: "70%",
    "rural-residence": "65%",
    "urban-residence": "81%",
    "source-data": "Multiple Indicator Cluster Survey",
    "source-time-period": "2011-12",
  },
  {
    ISO3: "BRA",
    "countries-and-areas": "Brazil",
    region: "LAC",
    "unicef-sub-region": "LAC",
    "income-group": "Upper middle income (UM)",
    total: "84%",
    "rural-residence": "55%",
    "urban-residence": "90%",
    "source-data": "Brazil Continuous National Household Sample Survey (Continuous PNAD) 2018, IBGE.",
    "source-time-period": "2018",
  },
  {
    ISO3: "BGR",
    "countries-and-areas": "Bulgaria",
    region: "ECA",
    "unicef-sub-region": "EECA",
    "income-group": "Upper middle income (UM)",
    total: "83%",
    "rural-residence": "83%",
    "urban-residence": "83%",
    "source-data": "Bulgarian Longitudinal Inclusive Society Survey (BLISS) 2013",
    "source-time-period": "2013",
  },
  {
    ISO3: "BFA",
    "countries-and-areas": "Burkina Faso",
    region: "SSA",
    "unicef-sub-region": "WCA",
    "income-group": "Low income (L)",
    total: "2%",
    "rural-residence": "0%",
    "urban-residence": "5%",
    "source-data": "Demographic and Health Survey",
    "source-time-period": "2010",
  },
  {
    ISO3: "CMR",
    "countries-and-areas": "Cameroon",
    region: "SSA",
    "unicef-sub-region": "WCA",
    "income-group": "Lower middle income (LM)",
    total: "7%",
    "rural-residence": "0%",
    "urban-residence": "12%",
    "source-data": "Multiple Indicator Cluster Survey",
    "source-time-period": "2014",
  },
  {
    ISO3: "CAF",
    "countries-and-areas": "Central African Republic",
    region: "SSA",
    "unicef-sub-region": "WCA",
    "income-group": "Low income (L)",
    total: "6%",
    "rural-residence": "1%",
    "urban-residence": "12%",
    "source-data": "Multiple Indicator Cluster Survey",
    "source-time-period": "2018-19",
  },
  {
    ISO3: "TCD",
    "countries-and-areas": "Chad",
    region: "SSA",
    "unicef-sub-region": "WCA",
    "income-group": "Low income (L)",
    total: "3%",
    "rural-residence": "1%",
    "urban-residence": "12%",
    "source-data": "Multiple Indicator Cluster Survey",
    "source-time-period": "2019",
  },
  {
    ISO3: "CHL",
    "countries-and-areas": "Chile",
    region: "LAC",
    "unicef-sub-region": "LAC",
    "income-group": "High income (H)",
    total: "87%",
    "rural-residence": "72%",
    "urban-residence": "90%",
    "source-data": "CASEN",
    "source-time-period": "2017",
  },
  {
    ISO3: "CHN",
    "countries-and-areas": "China",
    region: "EAP",
    "unicef-sub-region": "EAP",
    "income-group": "Upper middle income (UM)",
    total: "76%",
    "rural-residence": "58%",
    "urban-residence": "91%",
    "source-data": "CHARLS 2018",
    "source-time-period": "2018",
  },
  {
    ISO3: "COL",
    "countries-and-areas": "Colombia",
    region: "LAC",
    "unicef-sub-region": "LAC",
    "income-group": "Upper middle income (UM)",
    total: "43%",
    "rural-residence": "7%",
    "urban-residence": "54%",
    "source-data": "Demographic and Health Survey",
    "source-time-period": "2015-16",
  },
  {
    ISO3: "CRI",
    "countries-and-areas": "Costa Rica",
    region: "LAC",
    "unicef-sub-region": "LAC",
    "income-group": "Upper middle income (UM)",
    total: "77%",
    "rural-residence": "60%",
    "urban-residence": "86%",
    "source-data": "Multiple Indicator Cluster Survey",
    "source-time-period": "2018",
  },
  {
    ISO3: "CIV",
    "countries-and-areas": "Côte d'Ivoire",
    region: "SSA",
    "unicef-sub-region": "WCA",
    "income-group": "Lower middle income (LM)",
    total: "3%",
    "rural-residence": "2%",
    "urban-residence": "5%",
    "source-data": "Multiple Indicator Cluster Survey",
    "source-time-period": "2016",
  },
  {
    ISO3: "CUB",
    "countries-and-areas": "Cuba",
    region: "LAC",
    "unicef-sub-region": "LAC",
    "income-group": "Upper middle income (UM)",
    total: "4%",
    "rural-residence": "1%",
    "urban-residence": "5%",
    "source-data": "Multiple Indicator Cluster Survey",
    "source-time-period": "2019",
  },
  {
    ISO3: "COD",
    "countries-and-areas": "Democratic Republic of the Congo",
    region: "SSA",
    "unicef-sub-region": "WCA",
    "income-group": "Low income (L)",
    total: "1%",
    "rural-residence": "0%",
    "urban-residence": "3%",
    "source-data": "Multiple Indicator Cluster Survey",
    "source-time-period": "2017-18",
  },
  {
    ISO3: "DJI",
    "countries-and-areas": "Djibouti",
    region: "SSA",
    "unicef-sub-region": "ESA",
    "income-group": "Lower middle income (LM)",
    total: "9%",
    "rural-residence": "2%",
    "urban-residence": "16%",
    "source-data":
      "Enquête Djiboutienne Auprès des Ménages pour les Indicateurs Sociaux 2012 - Données pour utilisation publique",
    "source-time-period": "2012",
  },
  {
    ISO3: "DOM",
    "countries-and-areas": "Dominican Republic",
    region: "LAC",
    "unicef-sub-region": "LAC",
    "income-group": "Upper middle income (UM)",
    total: "27%",
    "rural-residence": "11%",
    "urban-residence": "32%",
    "source-data": "Multiple Indicator Cluster Survey",
    "source-time-period": "2014",
  },
  {
    ISO3: "GMB",
    "countries-and-areas": "Gambia",
    region: "SSA",
    "unicef-sub-region": "WCA",
    "income-group": "Low income (L)",
    total: "72%",
    "rural-residence": "51%",
    "urban-residence": "80%",
    "source-data": "Multiple Indicator Cluster Survey",
    "source-time-period": "2018",
  },
  {
    ISO3: "GEO",
    "countries-and-areas": "Georgia",
    region: "ECA",
    "unicef-sub-region": "EECA",
    "income-group": "Upper middle income (UM)",
    total: "88%",
    "rural-residence": "75%",
    "urban-residence": "96%",
    "source-data": "Multiple Indicator Cluster Survey",
    "source-time-period": "2018",
  },
  {
    ISO3: "GHA",
    "countries-and-areas": "Ghana",
    region: "SSA",
    "unicef-sub-region": "WCA",
    "income-group": "Lower middle income (LM)",
    total: "20%",
    "rural-residence": "13%",
    "urban-residence": "28%",
    "source-data": "Multiple Indicator Cluster Survey",
    "source-time-period": "2017-18",
  },
  {
    ISO3: "GTM",
    "countries-and-areas": "Guatemala",
    region: "LAC",
    "unicef-sub-region": "LAC",
    "income-group": "Upper middle income (UM)",
    total: "12%",
    "rural-residence": "4%",
    "urban-residence": "24%",
    "source-data": "Demographic and Health Survey",
    "source-time-period": "2014-15",
  },
  {
    ISO3: "GNB",
    "countries-and-areas": "Guinea-Bissau",
    region: "SSA",
    "unicef-sub-region": "WCA",
    "income-group": "Low income (L)",
    total: "3%",
    "rural-residence": "2%",
    "urban-residence": "4%",
    "source-data": "Multiple Indicator Cluster Survey",
    "source-time-period": "2018-19",
  },
  {
    ISO3: "HTI",
    "countries-and-areas": "Haiti",
    region: "LAC",
    "unicef-sub-region": "LAC",
    "income-group": "Low income (L)",
    total: "26%",
    "rural-residence": "15%",
    "urban-residence": "41%",
    "source-data": "Demographic and Health Survey",
    "source-time-period": "2016-17",
  },
  {
    ISO3: "IND",
    "countries-and-areas": "India",
    region: "SA",
    "unicef-sub-region": "SA",
    "income-group": "Lower middle income (LM)",
    total: "12%",
    "rural-residence": "7%",
    "urban-residence": "21%",
    "source-data": "Demographic and Health Survey",
    "source-time-period": "2015-16",
  },
  {
    ISO3: "IDN",
    "countries-and-areas": "Indonesia",
    region: "EAP",
    "unicef-sub-region": "EAP",
    "income-group": "Lower middle income (LM)",
    total: "23%",
    "rural-residence": "13%",
    "urban-residence": "30%",
    "source-data": "SUSENAS",
    "source-time-period": "2019",
  },
  {
    ISO3: "IRQ",
    "countries-and-areas": "Iraq",
    region: "MENA",
    "unicef-sub-region": "MENA",
    "income-group": "Upper middle income (UM)",
    total: "56%",
    "rural-residence": "43%",
    "urban-residence": "62%",
    "source-data": "Multiple Indicator Cluster Survey",
    "source-time-period": "2018",
  },
  {
    ISO3: "ITA",
    "countries-and-areas": "Italy",
    region: "ECA",
    "unicef-sub-region": "WE",
    "income-group": "High income (H)",
    total: "75%",
    "source-data": "Multiscopo sulle famiglie: aspetti della vita quotidiana",
    "source-time-period": "2018",
  },
  {
    ISO3: "JPN",
    "countries-and-areas": "Japan",
    region: "EAP",
    "unicef-sub-region": "EAP",
    "income-group": "High income (H)",
    total: "88%",
    "rural-residence": "88%",
    "urban-residence": "87%",
    "source-data": "The Japan Household Panel Survey",
    "source-time-period": "2018",
  },
  {
    ISO3: "JOR",
    "countries-and-areas": "Jordan",
    region: "MENA",
    "unicef-sub-region": "MENA",
    "income-group": "Upper middle income (UM)",
    total: "42%",
    "rural-residence": "41%",
    "urban-residence": "42%",
    "source-data": "Demographic and Health Survey",
    "source-time-period": "2017-18",
  },
  {
    ISO3: "KEN",
    "countries-and-areas": "Kenya",
    region: "SSA",
    "unicef-sub-region": "ESA",
    "income-group": "Lower middle income (LM)",
    total: "39%",
    "urban-residence": "29%",
    "source-data": "STEP Skills Measurement Household Survey 2013 (Wave 2)",
    "source-time-period": "2013",
  },
  {
    ISO3: "KIR",
    "countries-and-areas": "Kiribati",
    region: "EAP",
    "unicef-sub-region": "EAP",
    "income-group": "Lower middle income (LM)",
    total: "59%",
    "rural-residence": "36%",
    "urban-residence": "77%",
    "source-data": "Multiple Indicator Cluster Survey",
    "source-time-period": "2018-19",
  },
  {
    ISO3: "KGZ",
    "countries-and-areas": "Kyrgyzstan",
    region: "ECA",
    "unicef-sub-region": "EECA",
    "income-group": "Lower middle income (LM)",
    total: "77%",
    "rural-residence": "72%",
    "urban-residence": "86%",
    "source-data": "Multiple Indicator Cluster Survey",
    "source-time-period": "2018",
  },
  {
    ISO3: "LAO",
    "countries-and-areas": "Lao People's Democratic Republic",
    region: "EAP",
    "unicef-sub-region": "EAP",
    "income-group": "Lower middle income (LM)",
    total: "2%",
    "rural-residence": "1%",
    "urban-residence": "4%",
    "source-data": "Multiple Indicator Cluster Survey",
    "source-time-period": "2017",
  },
  {
    ISO3: "LSO",
    "countries-and-areas": "Lesotho",
    region: "SSA",
    "unicef-sub-region": "ESA",
    "income-group": "Lower middle income (LM)",
    total: "38%",
    "rural-residence": "29%",
    "urban-residence": "56%",
    "source-data": "Multiple Indicator Cluster Survey",
    "source-time-period": "2018",
  },
  {
    ISO3: "MDG",
    "countries-and-areas": "Madagascar",
    region: "SSA",
    "unicef-sub-region": "ESA",
    "income-group": "Low income (L)",
    total: "16%",
    "rural-residence": "10%",
    "urban-residence": "35%",
    "source-data": "Multiple Indicator Cluster Survey",
    "source-time-period": "2018",
  },
  {
    ISO3: "MDV",
    "countries-and-areas": "Maldives",
    region: "SA",
    "unicef-sub-region": "SA",
    "income-group": "Upper middle income (UM)",
    total: "73%",
    "rural-residence": "70%",
    "urban-residence": "77%",
    "source-data": "Demographic and Health Survey",
    "source-time-period": "2016-17",
  },
  {
    ISO3: "MLI",
    "countries-and-areas": "Mali",
    region: "SSA",
    "unicef-sub-region": "WCA",
    "income-group": "Low income (L)",
    total: "8%",
    "rural-residence": "4%",
    "urban-residence": "17%",
    "source-data": "Multiple Indicator Cluster Survey",
    "source-time-period": "2015",
  },
  {
    ISO3: "MRT",
    "countries-and-areas": "Mauritania",
    region: "SSA",
    "unicef-sub-region": "WCA",
    "income-group": "Lower middle income (LM)",
    total: "4%",
    "rural-residence": "1%",
    "urban-residence": "7%",
    "source-data": "Multiple Indicator Cluster Survey",
    "source-time-period": "2015",
  },
  {
    ISO3: "MNG",
    "countries-and-areas": "Mongolia",
    region: "EAP",
    "unicef-sub-region": "EAP",
    "income-group": "Lower middle income (LM)",
    total: "38%",
    "rural-residence": "10%",
    "urban-residence": "51%",
    "source-data": "Multiple Indicator Cluster Survey",
    "source-time-period": "2018",
  },
  {
    ISO3: "MNE",
    "countries-and-areas": "Montenegro",
    region: "ECA",
    "unicef-sub-region": "EECA",
    "income-group": "Upper middle income (UM)",
    total: "82%",
    "rural-residence": "76%",
    "urban-residence": "85%",
    "source-data": "Multiple Indicator Cluster Survey",
    "source-time-period": "2018-19",
  },
  {
    ISO3: "MAR",
    "countries-and-areas": "Morocco",
    region: "MENA",
    "unicef-sub-region": "MENA",
    "income-group": "Lower middle income (LM)",
    total: "19%",
    "rural-residence": "12%",
    "urban-residence": "25%",
    "source-data": "Morocco Household and Youth Survey 2010",
    "source-time-period": "2010",
  },
  {
    ISO3: "NAM",
    "countries-and-areas": "Namibia",
    region: "SSA",
    "unicef-sub-region": "ESA",
    "income-group": "Upper middle income (UM)",
    total: "9%",
    "rural-residence": "1%",
    "urban-residence": "17%",
    "source-data": "Demographic and Health Survey",
    "source-time-period": "2013",
  },
  {
    ISO3: "NPL",
    "countries-and-areas": "Nepal",
    region: "SA",
    "unicef-sub-region": "SA",
    "income-group": "Low income (L)",
    total: "49%",
    "rural-residence": "34%",
    "urban-residence": "57%",
    "source-data": "Multiple Indicator Cluster Survey",
    "source-time-period": "2076",
  },
  {
    ISO3: "NIC",
    "countries-and-areas": "Nicaragua",
    region: "LAC",
    "unicef-sub-region": "LAC",
    "income-group": "Lower middle income (LM)",
    total: "4%",
    "source-data": "Nicaragua National Demographic and Health Survey 2011-2012",
    "source-time-period": "2011-12",
  },
  {
    ISO3: "NER",
    "countries-and-areas": "Niger",
    region: "SSA",
    "unicef-sub-region": "WCA",
    "income-group": "Low income (L)",
    total: "6%",
    "source-data": "National Survey on Household Living Conditions and Agriculture 2014, Wave 2 Panel Data",
    "source-time-period": "2014-15",
  },
  {
    ISO3: "NGA",
    "countries-and-areas": "Nigeria",
    region: "SSA",
    "unicef-sub-region": "WCA",
    "income-group": "Lower middle income (LM)",
    total: "4%",
    "source-data": "General Household Survey, Panel 2018-2019, Wave 4",
    "source-time-period": "2018-2019",
  },
  {
    ISO3: "PAK",
    "countries-and-areas": "Pakistan",
    region: "SA",
    "unicef-sub-region": "SA",
    "income-group": "Lower middle income (LM)",
    total: "10%",
    "rural-residence": "4%",
    "urban-residence": "22%",
    "source-data": "Demographic and Health Survey",
    "source-time-period": "2017",
  },
  {
    ISO3: "PAN",
    "countries-and-areas": "Panama",
    region: "LAC",
    "unicef-sub-region": "LAC",
    "income-group": "High income (H)",
    total: "38%",
    "rural-residence": "15%",
    "urban-residence": "51%",
    "source-data": "Multiple Indicator Cluster Survey",
    "source-time-period": "2013",
  },
  {
    ISO3: "RUS",
    "countries-and-areas": "Russian Federation",
    region: "ECA",
    "unicef-sub-region": "EECA",
    "income-group": "Upper middle income (UM)",
    total: "90%",
    "rural-residence": "77%",
    "urban-residence": "96%",
    "source-data": "Russia Longitudinal Monitoring Survey, 2018",
    "source-time-period": "2018",
  },
  {
    ISO3: "LCA",
    "countries-and-areas": "Saint Lucia",
    region: "LAC",
    "unicef-sub-region": "LAC",
    "income-group": "Upper middle income (UM)",
    total: "51%",
    "rural-residence": "53%",
    "urban-residence": "43%",
    "source-data": "Multiple Indicator Cluster Survey",
    "source-time-period": "2012",
  },
  {
    ISO3: "STP",
    "countries-and-areas": "Sao Tome and Principe",
    region: "SSA",
    "unicef-sub-region": "WCA",
    "income-group": "Lower middle income (LM)",
    total: "46%",
    "rural-residence": "37%",
    "urban-residence": "51%",
    "source-data": "Multiple Indicator Cluster Survey",
    "source-time-period": "2019",
  },
  {
    ISO3: "SEN",
    "countries-and-areas": "Senegal",
    region: "SSA",
    "unicef-sub-region": "WCA",
    "income-group": "Lower middle income (LM)",
    total: "7%",
    "rural-residence": "3%",
    "urban-residence": "12%",
    "source-data": "Demographic and Health Survey",
    "source-time-period": "2017",
  },
  {
    ISO3: "SRB",
    "countries-and-areas": "Serbia",
    region: "ECA",
    "unicef-sub-region": "EECA",
    "income-group": "Upper middle income (UM)",
    total: "95%",
    "rural-residence": "91%",
    "urban-residence": "97%",
    "source-data": "Multiple Indicator Cluster Survey",
    "source-time-period": "2019",
  },
  {
    ISO3: "SLE",
    "countries-and-areas": "Sierra Leone",
    region: "SSA",
    "unicef-sub-region": "WCA",
    "income-group": "Low income (L)",
    total: "18%",
    "rural-residence": "5%",
    "urban-residence": "29%",
    "source-data": "Multiple Indicator Cluster Survey",
    "source-time-period": "2017",
  },
  {
    ISO3: "SOM",
    "countries-and-areas": "Somalia",
    region: "SSA",
    "unicef-sub-region": "ESA",
    "income-group": "Low income (L)",
    total: "14%",
    "source-data": "Somalia High Frequency Survey",
    "source-time-period": "2017-18",
  },
  {
    ISO3: "ZAF",
    "countries-and-areas": "South Africa",
    region: "SSA",
    "unicef-sub-region": "ESA",
    "income-group": "Upper middle income (UM)",
    total: "18%",
    "source-data": "South Africa Living Conditions Survey 2014-15",
    "source-time-period": "2014-15",
  },
  {
    ISO3: "SSD",
    "countries-and-areas": "South Sudan",
    region: "SSA",
    "unicef-sub-region": "ESA",
    "income-group": "Low income (L)",
    total: "1%",
    "rural-residence": "0%",
    "urban-residence": "1%",
    "source-data": "Multiple Indicator Cluster Survey",
    "source-time-period": "2010",
  },
  {
    ISO3: "LKA",
    "countries-and-areas": "Sri Lanka",
    region: "SA",
    "unicef-sub-region": "SA",
    "income-group": "Upper middle income (UM)",
    total: "73%",
    "rural-residence": "70%",
    "urban-residence": "89%",
    "source-data": "STEP Skills Measurement Household Survey 2012 (Wave 1)",
    "source-time-period": "2012",
  },
  {
    ISO3: "SDN",
    "countries-and-areas": "Sudan",
    region: "SSA",
    "unicef-sub-region": "ESA",
    "income-group": "Lower middle income (LM)",
    total: "5%",
    "rural-residence": "2%",
    "urban-residence": "12%",
    "source-data": "Multiple Indicator Cluster Survey",
    "source-time-period": "2014",
  },
  {
    ISO3: "SUR",
    "countries-and-areas": "Suriname",
    region: "LAC",
    "unicef-sub-region": "LAC",
    "income-group": "Upper middle income (UM)",
    total: "55%",
    "rural-residence": "44%",
    "urban-residence": "59%",
    "source-data": "Multiple Indicator Cluster Survey",
    "source-time-period": "2018",
  },
  {
    ISO3: "TJK",
    "countries-and-areas": "Tajikistan",
    region: "ECA",
    "unicef-sub-region": "EECA",
    "income-group": "Low income (L)",
    total: "26%",
    "rural-residence": "21%",
    "urban-residence": "42%",
    "source-data": "Demographic and Health Survey",
    "source-time-period": "2017",
  },
  {
    ISO3: "THA",
    "countries-and-areas": "Thailand",
    region: "EAP",
    "unicef-sub-region": "EAP",
    "income-group": "Upper middle income (UM)",
    total: "77%",
    "rural-residence": "73%",
    "urban-residence": "83%",
    "source-data": "Multiple Indicator Cluster Survey",
    "source-time-period": "2562",
  },
  {
    ISO3: "MKD",
    "countries-and-areas": "North Macedonia",
    region: "ECA",
    "unicef-sub-region": "EECA",
    "income-group": "Upper middle income (UM)",
    total: "93%",
    "rural-residence": "92%",
    "urban-residence": "94%",
    "source-data": "Multiple Indicator Cluster Survey",
    "source-time-period": "2018-19",
  },
  {
    ISO3: "TGO",
    "countries-and-areas": "Togo",
    region: "SSA",
    "unicef-sub-region": "WCA",
    "income-group": "Low income (L)",
    total: "31%",
    "rural-residence": "11%",
    "urban-residence": "56%",
    "source-data": "Multiple Indicator Cluster Survey",
    "source-time-period": "2017",
  },
  {
    ISO3: "TON",
    "countries-and-areas": "Tonga",
    region: "EAP",
    "unicef-sub-region": "EAP",
    "income-group": "Upper middle income (UM)",
    total: "91%",
    "rural-residence": "89%",
    "urban-residence": "96%",
    "source-data": "Multiple Indicator Cluster Survey",
    "source-time-period": "2019",
  },
  {
    ISO3: "TTO",
    "countries-and-areas": "Trinidad and Tobago",
    region: "LAC",
    "unicef-sub-region": "LAC",
    "income-group": "High income (H)",
    total: "51%",
    "rural-residence": "41%",
    "urban-residence": "60%",
    "source-data": "Multiple Indicator Cluster Survey",
    "source-time-period": "2011",
  },
  {
    ISO3: "TUN",
    "countries-and-areas": "Tunisia",
    region: "MENA",
    "unicef-sub-region": "MENA",
    "income-group": "Lower middle income (LM)",
    total: "45%",
    "rural-residence": "26%",
    "urban-residence": "54%",
    "source-data": "Multiple Indicator Cluster Survey",
    "source-time-period": "2018",
  },
  {
    ISO3: "TUR",
    "countries-and-areas": "Turkey",
    region: "ECA",
    "unicef-sub-region": "EECA",
    "income-group": "Upper middle income (UM)",
    total: "40%",
    "rural-residence": "16%",
    "urban-residence": "47%",
    "source-data": "Demographic and Health Survey",
    "source-time-period": "2013",
  },
  {
    ISO3: "TKM",
    "countries-and-areas": "Turkmenistan",
    region: "ECA",
    "unicef-sub-region": "EECA",
    "income-group": "Upper middle income (UM)",
    total: "52%",
    "rural-residence": "43%",
    "urban-residence": "64%",
    "source-data": "Multiple Indicator Cluster Survey",
    "source-time-period": "2019",
  },
  {
    ISO3: "UGA",
    "countries-and-areas": "Uganda",
    region: "SSA",
    "unicef-sub-region": "ESA",
    "income-group": "Low income (L)",
    total: "1%",
    "rural-residence": "0%",
    "urban-residence": "4%",
    "source-data": "LSMS",
    "source-time-period": "2015",
  },
  {
    ISO3: "UKR",
    "countries-and-areas": "Ukraine",
    region: "ECA",
    "unicef-sub-region": "EECA",
    "income-group": "Lower middle income (LM)",
    total: "79%",
    "urban-residence": "79%",
    "source-data": "STEP Skills Measurement Household Survey 2013 (Wave 1)",
    "source-time-period": "2013",
  },
  {
    ISO3: "GBR",
    "countries-and-areas": "United Kingdom",
    region: "ECA",
    "unicef-sub-region": "WE",
    "income-group": "High income (H)",
    total: "99%",
    "source-data":
      "UK Data Archive Information for the Study 8298. Statistical Bulletin: Internet Access – Households and Individuals, 2016.",
    "source-time-period": "2016",
  },
  {
    ISO3: "URY",
    "countries-and-areas": "Uruguay",
    region: "LAC",
    "unicef-sub-region": "LAC",
    "income-group": "High income (H)",
    total: "70%",
    "rural-residence": "48%",
    "urban-residence": "73%",
    "source-data": "Multiple Indicator Cluster Survey",
    "source-time-period": "2012-99",
  },
  {
    ISO3: "UZB",
    "countries-and-areas": "Uzbekistan",
    region: "ECA",
    "unicef-sub-region": "EECA",
    "income-group": "Lower middle income (LM)",
    total: "22%",
    "rural-residence": "17%",
    "urban-residence": "38%",
    "source-data": "UNICEF Nutrition Survey 2017",
    "source-time-period": "2017",
  },
  {
    ISO3: "VNM",
    "countries-and-areas": "Viet Nam",
    region: "EAP",
    "unicef-sub-region": "EAP",
    "income-group": "Lower middle income (LM)",
    total: "67%",
    "urban-residence": "67%",
    "source-data": "STEP Skills Measurement Household Survey 2012 (Wave 1)",
    "source-time-period": "2012",
  },
  {
    ISO3: "ZMB",
    "countries-and-areas": "Zambia",
    region: "SSA",
    "unicef-sub-region": "ESA",
    "income-group": "Lower middle income (LM)",
    total: "7%",
    "rural-residence": "3%",
    "urban-residence": "14%",
    "source-data": "Demographic and Health Survey",
    "source-time-period": "2018-19",
  },
  {
    ISO3: "ZWE",
    "countries-and-areas": "Zimbabwe",
    region: "SSA",
    "unicef-sub-region": "ESA",
    "income-group": "Lower middle income (LM)",
    total: "29%",
    "rural-residence": "20%",
    "urban-residence": "51%",
    "source-data": "Multiple Indicator Cluster Survey",
    "source-time-period": "2018-19",
  },
];
